name: Build and deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  EXCLUDE_PREFIX: 'chore(release)'

jobs:
  get_env:
    uses: ./.github/workflows/env.yaml
  build_docker_image:
    name: Build Docker image and push to local registry
    runs-on: bolte-runner
    needs: get_env
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ needs.get_env.outputs.registry_url }}/${{ needs.get_env.outputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
  build_test_executable:
    name: Build test executable
    needs: [get_env, build_docker_image]
    runs-on: bolte-runner
    container:
      image: ${{ needs.build_docker_image.outputs.tags }}
    steps:
      - name: Prepare
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "IDF_PATH=$IDF_PATH" >> $GITHUB_ENV
          echo "IDF_PYTHON_ENV_PATH=$IDF_PYTHON_ENV_PATH" >> $GITHUB_ENV
          echo "ESP-IDF version: $(idf.py --version)"
      - name: Copy hello_world example
        run: cp -r $IDF_PATH/examples/get-started/hello_world /tmp/hello_world
      - name: Set Target
        run: idf.py -C /tmp/hello_world set-target esp32c6
      - name: Build
        run: idf.py -C /tmp/hello_world build
  release:
    name: Bump
    runs-on: bolte-runner
    needs: build_docker_image
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install --no-save semantic-release @semantic-release/git @semantic-release/github @semantic-release/changelog
      - name: Debug
        run: |
          pwd
          ls -la .git
          git remote -v
          git log --oneline -3
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

