name: Deploy a release to the local registry

on:
  workflow_dispatch:

jobs:
  get_env:
    uses: ./.github/workflows/env.yaml
  build_docker_image:
    name: Build Docker image and push to local registry
    runs-on: bolte-runner
    if: startsWith(github.ref, 'refs/tags/v')
    needs: get_env
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ needs.get_env.outputs.registry_url }}/${{ needs.get_env.outputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
